#!/usr/bin/env python3
"""
HTML Exporter - Export analysis results to interactive HTML format
"""

import json
from pathlib import Path
from typing import Dict, List, Any
from datetime import datetime

class HTMLExporter:
    """Exports analysis results to interactive HTML format."""
    
    def export(self, result: Any, output_dir: Path):
        """Export analysis results to HTML files."""
        print("   🌐 Exporting HTML files...")
        
        # Export main dashboard
        self._export_dashboard(result, output_dir)
        
        # Export detailed analysis pages
        self._export_file_analysis_page(result, output_dir)
        self._export_category_analysis_page(result, output_dir)
        self._export_duplicate_analysis_page(result, output_dir)
        self._export_depth_analysis_page(result, output_dir)
        
        # Export GitHub analysis page (if available)
        if hasattr(result, 'github_structure') and result.github_structure:
            self._export_github_analysis_page(result, output_dir)
        
        # Export codex analysis page (if available)
        if hasattr(result, 'codex_configs') and result.codex_configs:
            self._export_codex_analysis_page(result, output_dir)
        
        print("   ✅ HTML export complete")
    
    def _export_dashboard(self, result: Any, output_dir: Path):
        """Export main dashboard HTML."""
        html_path = output_dir / "dashboard.html"
        
        html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Deep Research Tool - Dashboard</title>
    <style>
        {self._get_css_styles()}
    </style>
</head>
<body>
    <div class="container">
        <header class="header">
            <h1>🔍 Deep Research Tool Dashboard</h1>
            <p class="subtitle">Comprehensive folder structure analysis</p>
            <div class="timestamp">Analysis performed: {result.analysis_timestamp.strftime('%Y-%m-%d %H:%M:%S')}</div>
        </header>
        
        <div class="metrics-grid">
            <div class="metric-card">
                <div class="metric-value">{result.total_files:,}</div>
                <div class="metric-label">Total Files</div>
            </div>
            <div class="metric-card">
                <div class="metric-value">{result.total_directories:,}</div>
                <div class="metric-label">Directories</div>
            </div>
            <div class="metric-card">
                <div class="metric-value">{result.max_depth}</div>
                <div class="metric-label">Max Depth</div>
            </div>
            <div class="metric-card">
                <div class="metric-value">{len(result.duplicate_groups)}</div>
                <div class="metric-label">Duplicate Groups</div>
            </div>
        </div>
        
        <div class="content-grid">
            <div class="card">
                <h2>📊 File Categories</h2>
                <div class="chart-container">
                    {self._generate_category_chart(result.categories)}
                </div>
            </div>
            
            <div class="card">
                <h2>📁 Depth Distribution</h2>
                <div class="chart-container">
                    {self._generate_depth_chart(result.depth_distribution)}
                </div>
            </div>
        </div>
        
        <div class="content-grid">
            <div class="card">
                <h2>🔝 Top File Types</h2>
                <div class="list-container">
                    {self._generate_file_types_list(result.file_types)}
                </div>
            </div>
            
            <div class="card">
                <h2>📈 Size by Category</h2>
                <div class="list-container">
                    {self._generate_size_by_category_list(result.size_by_category)}
                </div>
            </div>
        </div>
        
        <div class="navigation">
            <h2>📋 Detailed Analysis</h2>
            <div class="nav-links">
                <a href="file_analysis.html" class="nav-link">📄 File Analysis</a>
                <a href="category_analysis.html" class="nav-link">📂 Category Analysis</a>
                <a href="duplicate_analysis.html" class="nav-link">🔄 Duplicate Analysis</a>
                <a href="depth_analysis.html" class="nav-link">📏 Depth Analysis</a>
                {self._get_github_nav_link(result)}
                {self._get_codex_nav_link(result)}
            </div>
        </div>
        
        <footer class="footer">
            <p>Generated by Deep Research Tool | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        </footer>
    </div>
    
    <script>
        {self._get_js_scripts()}
    </script>
</body>
</html>"""
        
        with open(html_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        print(f"     🌐 Dashboard: {html_path}")
    
    def _export_file_analysis_page(self, result: Any, output_dir: Path):
        """Export detailed file analysis page."""
        html_path = output_dir / "file_analysis.html"
        
        # Prepare file data
        file_data = []
        if hasattr(result, 'files') and result.files:
            for file_info in result.files:
                file_data.append({
                    'path': file_info.path,
                    'name': file_info.name,
                    'extension': file_info.extension,
                    'size': file_info.size,
                    'size_mb': round(file_info.size / (1024 * 1024), 2),
                    'category': file_info.category,
                    'depth': file_info.depth,
                    'modified_time': file_info.modified_time.isoformat(),
                    'is_duplicate': file_info.is_duplicate
                })
        
        html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>File Analysis - Deep Research Tool</title>
    <style>
        {self._get_css_styles()}
        .file-table {{ width: 100%; border-collapse: collapse; }}
        .file-table th, .file-table td {{ padding: 8px; text-align: left; border-bottom: 1px solid #ddd; }}
        .file-table th {{ background-color: #f5f5f5; }}
        .file-table tr:hover {{ background-color: #f9f9f9; }}
        .size-cell {{ text-align: right; }}
        .duplicate {{ background-color: #ffe6e6; }}
    </style>
</head>
<body>
    <div class="container">
        <header class="header">
            <h1>📄 File Analysis</h1>
            <p class="subtitle">Detailed analysis of all files</p>
            <a href="dashboard.html" class="back-link">← Back to Dashboard</a>
        </header>
        
        <div class="card">
            <h2>File Details</h2>
            <div class="table-container">
                <table class="file-table">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Path</th>
                            <th>Extension</th>
                            <th>Size (MB)</th>
                            <th>Category</th>
                            <th>Depth</th>
                            <th>Modified</th>
                            <th>Duplicate</th>
                        </tr>
                    </thead>
                    <tbody>
                        {self._generate_file_table_rows(file_data)}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>
</html>"""
        
        with open(html_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        print(f"     🌐 File analysis: {html_path}")
    
    def _export_category_analysis_page(self, result: Any, output_dir: Path):
        """Export category analysis page."""
        html_path = output_dir / "category_analysis.html"
        
        html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Category Analysis - Deep Research Tool</title>
    <style>
        {self._get_css_styles()}
        .category-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 20px; }}
        .category-card {{ background: white; border-radius: 8px; padding: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        .category-name {{ font-size: 1.2em; font-weight: bold; margin-bottom: 10px; }}
        .category-stats {{ display: flex; justify-content: space-between; margin-bottom: 10px; }}
        .progress-bar {{ width: 100%; height: 20px; background-color: #f0f0f0; border-radius: 10px; overflow: hidden; }}
        .progress-fill {{ height: 100%; background-color: #4CAF50; transition: width 0.3s ease; }}
    </style>
</head>
<body>
    <div class="container">
        <header class="header">
            <h1>📂 Category Analysis</h1>
            <p class="subtitle">File distribution by category</p>
            <a href="dashboard.html" class="back-link">← Back to Dashboard</a>
        </header>
        
        <div class="category-grid">
            {self._generate_category_cards(result.categories, result.size_by_category, result.total_files)}
        </div>
    </div>
</body>
</html>"""
        
        with open(html_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        print(f"     🌐 Category analysis: {html_path}")
    
    def _export_duplicate_analysis_page(self, result: Any, output_dir: Path):
        """Export duplicate analysis page."""
        html_path = output_dir / "duplicate_analysis.html"
        
        html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Duplicate Analysis - Deep Research Tool</title>
    <style>
        {self._get_css_styles()}
        .duplicate-group {{ margin-bottom: 20px; padding: 15px; border: 1px solid #ddd; border-radius: 8px; }}
        .duplicate-group h3 {{ margin-top: 0; color: #d32f2f; }}
        .duplicate-files {{ margin-left: 20px; }}
        .duplicate-file {{ padding: 5px 0; border-bottom: 1px solid #eee; }}
        .duplicate-file:last-child {{ border-bottom: none; }}
        .representative {{ font-weight: bold; color: #2e7d32; }}
    </style>
</head>
<body>
    <div class="container">
        <header class="header">
            <h1>🔄 Duplicate Analysis</h1>
            <p class="subtitle">Duplicate file groups found</p>
            <a href="dashboard.html" class="back-link">← Back to Dashboard</a>
        </header>
        
        <div class="card">
            <h2>Duplicate Groups ({len(result.duplicate_groups)})</h2>
            {self._generate_duplicate_groups_html(result.duplicate_groups)}
        </div>
    </div>
</body>
</html>"""
        
        with open(html_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        print(f"     🌐 Duplicate analysis: {html_path}")
    
    def _export_depth_analysis_page(self, result: Any, output_dir: Path):
        """Export depth analysis page."""
        html_path = output_dir / "depth_analysis.html"
        
        html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Depth Analysis - Deep Research Tool</title>
    <style>
        {self._get_css_styles()}
        .depth-chart {{ display: flex; align-items: end; height: 300px; gap: 10px; margin: 20px 0; }}
        .depth-bar {{ background: linear-gradient(to top, #4CAF50, #8BC34A); border-radius: 4px 4px 0 0; min-width: 40px; display: flex; flex-direction: column; justify-content: end; }}
        .depth-label {{ text-align: center; margin-top: 10px; font-weight: bold; }}
        .depth-value {{ background: rgba(255,255,255,0.8); padding: 2px 6px; border-radius: 4px; margin: 5px; }}
    </style>
</head>
<body>
    <div class="container">
        <header class="header">
            <h1>📏 Depth Analysis</h1>
            <p class="subtitle">File distribution by directory depth</p>
            <a href="dashboard.html" class="back-link">← Back to Dashboard</a>
        </header>
        
        <div class="card">
            <h2>Depth Distribution</h2>
            <div class="depth-chart">
                {self._generate_depth_chart_bars(result.depth_distribution)}
            </div>
        </div>
    </div>
</body>
</html>"""
        
        with open(html_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        print(f"     🌐 Depth analysis: {html_path}")
    
    def _export_github_analysis_page(self, result: Any, output_dir: Path):
        """Export GitHub analysis page."""
        html_path = output_dir / "github_analysis.html"
        
        github_structure = result.github_structure
        health_score = github_structure.get('repository_health_score', 0)
        
        html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GitHub Analysis - Deep Research Tool</title>
    <style>
        {self._get_css_styles()}
        .health-score {{ font-size: 3em; font-weight: bold; text-align: center; margin: 20px 0; }}
        .health-excellent {{ color: #4CAF50; }}
        .health-good {{ color: #8BC34A; }}
        .health-fair {{ color: #FF9800; }}
        .health-poor {{ color: #f44336; }}
        .checklist {{ list-style: none; padding: 0; }}
        .checklist li {{ padding: 10px; margin: 5px 0; border-radius: 4px; }}
        .checklist .checked {{ background-color: #e8f5e8; color: #2e7d32; }}
        .checklist .unchecked {{ background-color: #ffebee; color: #c62828; }}
        .checklist .checked::before {{ content: "✅ "; }}
        .checklist .unchecked::before {{ content: "❌ "; }}
    </style>
</head>
<body>
    <div class="container">
        <header class="header">
            <h1>🐙 GitHub Analysis</h1>
            <p class="subtitle">Repository structure and health analysis</p>
            <a href="dashboard.html" class="back-link">← Back to Dashboard</a>
        </header>
        
        <div class="card">
            <h2>Repository Health Score</h2>
            <div class="health-score {self._get_health_score_class(health_score)}">{health_score}/100</div>
        </div>
        
        <div class="card">
            <h2>Essential Files Checklist</h2>
            <ul class="checklist">
                {self._generate_github_checklist(github_structure)}
            </ul>
        </div>
        
        <div class="card">
            <h2>Code Organization</h2>
            <div class="metrics-grid">
                <div class="metric-card">
                    <div class="metric-value">{len(github_structure.get('code_files', []))}</div>
                    <div class="metric-label">Code Files</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{len(github_structure.get('test_files', []))}</div>
                    <div class="metric-label">Test Files</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{len(github_structure.get('config_files', []))}</div>
                    <div class="metric-label">Config Files</div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>"""
        
        with open(html_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        print(f"     🌐 GitHub analysis: {html_path}")
    
    def _export_codex_analysis_page(self, result: Any, output_dir: Path):
        """Export codex analysis page."""
        html_path = output_dir / "codex_analysis.html"
        
        html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Codex Analysis - Deep Research Tool</title>
    <style>
        {self._get_css_styles()}
        .codex-config {{ background: #f8f9fa; border: 1px solid #dee2e6; border-radius: 8px; padding: 20px; margin: 10px 0; }}
        .codex-config h3 {{ margin-top: 0; color: #495057; }}
        .config-json {{ background: #2d3748; color: #e2e8f0; padding: 15px; border-radius: 4px; overflow-x: auto; }}
        .ai-tool {{ display: inline-block; background: #007bff; color: white; padding: 5px 10px; border-radius: 4px; margin: 5px; }}
    </style>
</head>
<body>
    <div class="container">
        <header class="header">
            <h1>🤖 Codex Analysis</h1>
            <p class="subtitle">AI tool configurations and recommendations</p>
            <a href="dashboard.html" class="back-link">← Back to Dashboard</a>
        </header>
        
        <div class="card">
            <h2>AI Tool Configurations</h2>
            {self._generate_codex_configs_html(result.codex_configs)}
        </div>
    </div>
</body>
</html>"""
        
        with open(html_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        print(f"     🌐 Codex analysis: {html_path}")
    
    def _get_css_styles(self) -> str:
        """Get CSS styles for HTML pages."""
        return """
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; background: #f5f5f5; }
        .container { max-width: 1200px; margin: 0 auto; padding: 20px; }
        .header { background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); margin-bottom: 20px; text-align: center; }
        .header h1 { font-size: 2.5em; margin-bottom: 10px; color: #2c3e50; }
        .subtitle { color: #7f8c8d; font-size: 1.2em; }
        .timestamp { color: #95a5a6; font-size: 0.9em; margin-top: 10px; }
        .metrics-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin-bottom: 30px; }
        .metric-card { background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); text-align: center; }
        .metric-value { font-size: 2.5em; font-weight: bold; color: #3498db; margin-bottom: 5px; }
        .metric-label { color: #7f8c8d; font-size: 0.9em; text-transform: uppercase; letter-spacing: 1px; }
        .content-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(400px, 1fr)); gap: 20px; margin-bottom: 30px; }
        .card { background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        .card h2 { margin-bottom: 15px; color: #2c3e50; }
        .chart-container { height: 300px; display: flex; align-items: center; justify-content: center; }
        .list-container { max-height: 300px; overflow-y: auto; }
        .list-item { padding: 10px; border-bottom: 1px solid #eee; display: flex; justify-content: space-between; }
        .list-item:last-child { border-bottom: none; }
        .navigation { background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); margin-bottom: 20px; }
        .nav-links { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 10px; }
        .nav-link { display: block; padding: 15px; background: #3498db; color: white; text-decoration: none; border-radius: 4px; text-align: center; transition: background 0.3s; }
        .nav-link:hover { background: #2980b9; }
        .back-link { color: #3498db; text-decoration: none; font-weight: bold; }
        .back-link:hover { text-decoration: underline; }
        .footer { text-align: center; color: #7f8c8d; margin-top: 30px; }
        """
    
    def _get_js_scripts(self) -> str:
        """Get JavaScript for interactive features."""
        return """
        // Add any interactive JavaScript here
        document.addEventListener('DOMContentLoaded', function() {
            // Initialize any interactive features
            console.log('Deep Research Tool Dashboard loaded');
        });
        """
    
    def _generate_category_chart(self, categories: Dict) -> str:
        """Generate HTML for category chart."""
        if not categories:
            return "<p>No category data available</p>"
        
        # Create a simple bar chart
        max_count = max(categories.values())
        chart_html = "<div style='display: flex; flex-direction: column; gap: 10px;'>"
        
        for category, count in sorted(categories.items(), key=lambda x: x[1], reverse=True)[:10]:
            width = (count / max_count) * 100
            chart_html += f"""
            <div style='display: flex; align-items: center; gap: 10px;'>
                <div style='min-width: 100px; font-size: 0.9em;'>{category}</div>
                <div style='flex: 1; background: #f0f0f0; height: 20px; border-radius: 10px; overflow: hidden;'>
                    <div style='background: #4CAF50; height: 100%; width: {width}%; transition: width 0.3s ease;'></div>
                </div>
                <div style='min-width: 50px; text-align: right; font-weight: bold;'>{count:,}</div>
            </div>
            """
        
        chart_html += "</div>"
        return chart_html
    
    def _generate_depth_chart(self, depth_distribution: Dict) -> str:
        """Generate HTML for depth chart."""
        if not depth_distribution:
            return "<p>No depth data available</p>"
        
        max_count = max(depth_distribution.values())
        chart_html = "<div style='display: flex; align-items: end; height: 200px; gap: 5px;'>"
        
        for depth in sorted(depth_distribution.keys()):
            count = depth_distribution[depth]
            height = (count / max_count) * 180
            chart_html += f"""
            <div style='display: flex; flex-direction: column; align-items: center;'>
                <div style='background: #3498db; width: 30px; height: {height}px; border-radius: 4px 4px 0 0;'></div>
                <div style='margin-top: 5px; font-size: 0.8em; font-weight: bold;'>{depth}</div>
                <div style='font-size: 0.7em; color: #666;'>{count}</div>
            </div>
            """
        
        chart_html += "</div>"
        return chart_html
    
    def _generate_file_types_list(self, file_types: Dict) -> str:
        """Generate HTML for file types list."""
        if not file_types:
            return "<p>No file type data available</p>"
        
        html = ""
        for ext, count in sorted(file_types.items(), key=lambda x: x[1], reverse=True)[:15]:
            html += f"""
            <div class="list-item">
                <span>.{ext}</span>
                <span>{count:,}</span>
            </div>
            """
        return html
    
    def _generate_size_by_category_list(self, size_by_category: Dict) -> str:
        """Generate HTML for size by category list."""
        if not size_by_category:
            return "<p>No size data available</p>"
        
        total_size = sum(size_by_category.values())
        html = ""
        for category, size in sorted(size_by_category.items(), key=lambda x: x[1], reverse=True)[:10]:
            size_mb = round(size / (1024 * 1024), 2)
            percentage = round((size / total_size) * 100, 1) if total_size > 0 else 0
            html += f"""
            <div class="list-item">
                <span>{category}</span>
                <span>{size_mb} MB ({percentage}%)</span>
            </div>
            """
        return html
    
    def _generate_file_table_rows(self, file_data: List[Dict]) -> str:
        """Generate HTML table rows for file data."""
        if not file_data:
            return "<tr><td colspan='8'>No file data available</td></tr>"
        
        html = ""
        for file_info in file_data[:100]:  # Limit to first 100 files
            duplicate_class = "duplicate" if file_info.get('is_duplicate', False) else ""
            html += f"""
            <tr class="{duplicate_class}">
                <td>{file_info.get('name', '')}</td>
                <td style='max-width: 300px; overflow: hidden; text-overflow: ellipsis;'>{file_info.get('path', '')}</td>
                <td>.{file_info.get('extension', '')}</td>
                <td class="size-cell">{file_info.get('size_mb', 0)}</td>
                <td>{file_info.get('category', '')}</td>
                <td>{file_info.get('depth', 0)}</td>
                <td>{file_info.get('modified_time', '')[:10]}</td>
                <td>{'Yes' if file_info.get('is_duplicate', False) else 'No'}</td>
            </tr>
            """
        return html
    
    def _generate_category_cards(self, categories: Dict, size_by_category: Dict, total_files: int) -> str:
        """Generate HTML for category cards."""
        if not categories:
            return "<p>No category data available</p>"
        
        html = ""
        for category, count in sorted(categories.items(), key=lambda x: x[1], reverse=True):
            size_bytes = size_by_category.get(category, 0)
            size_mb = round(size_bytes / (1024 * 1024), 2)
            percentage = round((count / total_files) * 100, 1) if total_files > 0 else 0
            
            html += f"""
            <div class="category-card">
                <div class="category-name">{category}</div>
                <div class="category-stats">
                    <span>{count:,} files</span>
                    <span>{size_mb} MB</span>
                </div>
                <div class="progress-bar">
                    <div class="progress-fill" style="width: {percentage}%"></div>
                </div>
                <div style="text-align: center; margin-top: 5px; font-size: 0.9em; color: #666;">
                    {percentage}% of files
                </div>
            </div>
            """
        return html
    
    def _generate_duplicate_groups_html(self, duplicate_groups: Dict) -> str:
        """Generate HTML for duplicate groups."""
        if not duplicate_groups:
            return "<p>No duplicate groups found</p>"
        
        html = ""
        for i, (content_hash, file_paths) in enumerate(duplicate_groups.items()):
            html += f"""
            <div class="duplicate-group">
                <h3>Group {i + 1} ({len(file_paths)} files)</h3>
                <div class="duplicate-files">
            """
            
            for j, file_path in enumerate(file_paths):
                representative_class = "representative" if j == 0 else ""
                html += f'<div class="duplicate-file {representative_class}">{file_path}</div>'
            
            html += """
                </div>
            </div>
            """
        
        return html
    
    def _generate_depth_chart_bars(self, depth_distribution: Dict) -> str:
        """Generate HTML bars for depth chart."""
        if not depth_distribution:
            return "<p>No depth data available</p>"
        
        max_count = max(depth_distribution.values())
        html = ""
        
        for depth in sorted(depth_distribution.keys()):
            count = depth_distribution[depth]
            height = (count / max_count) * 250
            html += f"""
            <div class="depth-bar" style="height: {height}px;">
                <div class="depth-value">{count}</div>
                <div class="depth-label">Depth {depth}</div>
            </div>
            """
        
        return html
    
    def _get_github_nav_link(self, result: Any) -> str:
        """Get GitHub navigation link if available."""
        if hasattr(result, 'github_structure') and result.github_structure:
            return '<a href="github_analysis.html" class="nav-link">🐙 GitHub Analysis</a>'
        return ""
    
    def _get_codex_nav_link(self, result: Any) -> str:
        """Get codex navigation link if available."""
        if hasattr(result, 'codex_configs') and result.codex_configs:
            return '<a href="codex_analysis.html" class="nav-link">🤖 Codex Analysis</a>'
        return ""
    
    def _get_health_score_class(self, score: int) -> str:
        """Get CSS class for health score."""
        if score >= 80:
            return "health-excellent"
        elif score >= 60:
            return "health-good"
        elif score >= 40:
            return "health-fair"
        else:
            return "health-poor"
    
    def _generate_github_checklist(self, github_structure: Dict) -> str:
        """Generate HTML for GitHub checklist."""
        items = [
            ('has_readme', 'README.md file'),
            ('has_license', 'LICENSE file'),
            ('has_contributing', 'CONTRIBUTING.md file'),
            ('has_gitignore', '.gitignore file'),
            ('has_github_workflows', 'GitHub Actions workflows'),
            ('has_issue_templates', 'Issue templates'),
            ('has_pr_template', 'Pull request template'),
            ('has_security_policy', 'Security policy')
        ]
        
        html = ""
        for key, description in items:
            checked = github_structure.get(key, False)
            class_name = "checked" if checked else "unchecked"
            html += f'<li class="{class_name}">{description}</li>'
        
        return html
    
    def _generate_codex_configs_html(self, codex_configs: Dict) -> str:
        """Generate HTML for codex configurations."""
        if not codex_configs:
            return "<p>No codex configurations available</p>"
        
        html = ""
        for tool, config in codex_configs.items():
            html += f"""
            <div class="codex-config">
                <h3>{tool.title()} Configuration</h3>
                <div class="config-json">
                    <pre>{json.dumps(config, indent=2)}</pre>
                </div>
            </div>
            """
        
        return html